### ISSUE TITLE
ERR: Request failed with status code 404

### ISSUE THREAD

**Issue by Aransh** [nitaybz/homebridge-tami4#14]
Since yesterday I've noticed my automations weren't working anymore, in homebridge logs I saw this error:
```
[6/6/2024, 9:40:03 AM] [Tami4] Boiling Water on תמי 4
[6/6/2024, 9:40:03 AM] [Tami4] Request failed with status code 404
[6/6/2024, 9:40:03 AM] [Tami4] ERROR: Boiling Water on תמי 4 Failed!
[6/6/2024, 9:40:03 AM] [Tami4] undefined
```

Tried to reinstall the plugin, now on startup I get:
```
[6/6/2024, 10:57:43 AM] [Tami4] Request failed with status code 404
[6/6/2024, 10:57:43 AM] [Tami4] ERR: Request failed with status code 404
```

Maybe API changes?

**Comment by Aransh** [comment]
Also important to note that trying to generate a new token through the config, it gets stuck hanging, while logs show:

```
[homebridge-tami4] {

  timestamp: 1717803196220,

  status: 404,

  error: 'Not Found',

  message: 'No message available',

  path: '/public/phone/generateOTP'

}
```

Which again leads me to believe it's indeed API changes

**Comment by Hershco** [comment]
I'm facing the same error unfortunately... 
Did you find a solution?

**Comment by Aransh** [comment]
Nothing yet, no

**Comment by oritor91** [comment]
Same here. On what platform are you running homebridge?

**Comment by Aransh** [comment]
For me Orange Pi Zero, but I don't think the platform matters as it seems like server side issue, plus it worked perfectly before

**Comment by Konyo-l** [comment]
same problem over here
maybe I can help with the api

**Comment by Aransh** [comment]
@nitaybz Are you aware of this issue or is this possibly a configuration issue on our end?

**Comment by Aransh** [comment]
Never mind, found this and guess it confirm my suspicion that there were API changes
https://github.com/Guy293/Tami4EdgeAPI/releases
Hope this plugin is updated to support these changes, appreciate your work either way 😃

**Comment by Hershco** [comment]
> Never mind, found this and guess it confirm my suspicion that there were API changes https://github.com/Guy293/Tami4EdgeAPI/releases Hope this plugin is updated to support these changes, appreciate your work either way 😃

Does the Tami4EdgeAPI support homebridge?

**Comment by adisharabani** [comment]
The plugin was indeed changed. 
I managed to fix it in my own environment - if someone or @nitaybz  wants to update the two files here it will be great:
(I had to update both tami4/api.js as well as homebridge-ui/server.js)

[Tami4Changes.zip](https://github.com/user-attachments/files/17262419/Tami4Changes.zip)

Please note that if you used the old version you might need to delete the old token from storage - or set it to initial one using: storage.setItem('tami4-token', token)

**Comment by Hershco** [comment]
> The plugin was indeed changed. I managed to fix it in my own environment - if someone or @nitaybz wants to update the two files here it will be great: (I had to update both tami4/api.js as well as homebridge-ui/server.js)
> 
> [Tami4Changes.zip](https://github.com/user-attachments/files/17262419/Tami4Changes.zip)
> 
> Please note that if you used the old version you might need to delete the old token from storage - or set it to initial one using: storage.setItem('tami4-token', token)

thanks, i replaced the files but there are still errors:

[04/10/2024, 23:04:24] [Tami4] Request failed with status code 403
[04/10/2024, 23:04:24] [Tami4] Can't Get Token: Request failed with status code 403
[04/10/2024, 23:04:24] [Tami4] The plugin could not refresh the status - ERROR OCCURRED:
[04/10/2024, 23:04:24] [Tami4] Request failed with status code 403

**Comment by Aransh** [comment]
> The plugin was indeed changed. 
> 
> I managed to fix it in my own environment - if someone or @nitaybz  wants to update the two files here it will be great:
> 
> (I had to update both tami4/api.js as well as homebridge-ui/server.js)
> 
> 
> 
> [Tami4Changes.zip](https://github.com/user-attachments/files/17262419/Tami4Changes.zip)
> 
> 
> 
> Please note that if you used the old version you might need to delete the old token from storage - or set it to initial one using: storage.setItem('tami4-token', token)
> 
> 
> 
> 

Thanks Adi! That worked for me 🙌🏼
Finally can get back to my automated routine 😄

Maybe consider opening a PR for Nitay, I can handle this next week if you're not familiar or don't care to be bothered, either way great job! Much appreciated

**Comment by Hershco** [comment]
> > The plugin was indeed changed.
> > I managed to fix it in my own environment - if someone or @nitaybz  wants to update the two files here it will be great:
> > (I had to update both tami4/api.js as well as homebridge-ui/server.js)
> > [Tami4Changes.zip](https://github.com/user-attachments/files/17262419/Tami4Changes.zip)
> > Please note that if you used the old version you might need to delete the old token from storage - or set it to initial one using: storage.setItem('tami4-token', token)
> 
> Thanks Adi! That worked for me 🙌🏼 Finally can get back to my automated routine 😄
> 
> Maybe consider opening a PR for Nitay, I can handle this next week if you're not familiar or don't care to be bothered, either way great job! Much appreciated

I’m honestly jealous of you… what am I doing wrong that it doesn’t work for me? 🥲

**Comment by Aransh** [comment]
> 
> I’m honestly jealous of you… what am I doing wrong that it doesn’t work for me? 🥲

Honestly no idea, did you Generate a new token like Adi said?

**Comment by Aransh** [comment]
Opened a PR - https://github.com/nitaybz/homebridge-tami4/pull/15

**Comment by adisharabani** [comment]
@Hershco - The issue you encounter is that you still have the old token (the way the code is written is that it doesn't override the token if such already exists). Fastest solution for you is to uninstall the plugin. Reinstall it. Add the two files and then continue to the configuration with your phone number. Let me know if it doesn't work.

**Comment by nitaybz** [comment]
The best way to do is actually from the code itself, you can add a variable, for example: 
```
"newToken": true
``` 

And if it's not there, delete the token or ignore it.

Once you do that, I'll merge the PR. Sorry I didn't have the time to work on it myself.
